### ISSUE TITLE
Unable to slide to Rating below 0.5

### ISSUE THREAD

**Issue by sagarrishabh** [saran2020/SlideRating#3]
I am trying to slide the rating below 0.5 I'm unable to move the rating to 0.

I feel letting the user rate 0 is a basic requirement and is mandatory for the lot of situations which needs to be allowed.

**Comment by saran2020** [comment]
I will take a look into this today. Meanwhile can you tell me what was the initial rating and max rating you were using?

**Comment by sagarrishabh** [comment]
I was using the initial rating of 2.5 and and max rating of 5 like your sample app
